---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://thisismk.github.io/scaling-octopus"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
...
